/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import juego.estructura.Pais;

/**
 *
 * @author Emanuel
 */
public class Dados extends javax.swing.JInternalFrame {  
    /**
     * Creates new form Dados
     */
    public Dados() {
        initComponents();
        this.setSize(195,300);    
        deshabilitar();     
    }
    public void deshabilitar(){
        dadoDefensa1.setVisible(false);
        dadoDefensa2.setVisible(false);
        dadoDefensa3.setVisible(false);
        dadoDefensa4.setVisible(false);
        dadoAtaque1.setVisible(false);
        dadoAtaque2.setVisible(false);
        dadoAtaque3.setVisible(false);
        dadoAtaque4.setVisible(false); 
    }
    public void cargarDados(int [] ataque, int[] defensa){
           
        if(ataque == null || defensa == null)return;
        QuickSort.quicksort(ataque, 0, ataque.length-1);
        QuickSort.quicksort(defensa, 0, defensa.length-1);
        mostrarDados(ataque,true);
        mostrarDados(defensa, false);
       
    }
    private void mostrarDados(int [] dados, boolean esAtaque){
        Component[] componentes = jPanel1.getComponents();        
        int num = 0;
        for(int i = dados.length-1; i>=0; i--){
            String nombre = "";
            num++;
            if(esAtaque){
                        nombre = "dadoAtaque"+num;
                    }
                    else{
                        nombre = "dadoDefensa"+num;
            }
            System.out.println(nombre);
            for(int j=0; j<componentes.length;j++){                
                if(componentes[j] instanceof JLabel) 
                { 
                    JLabel label = ((JLabel) componentes[j]);
                   
                    
                    if(label.getName()!=null && nombre.equalsIgnoreCase(label.getName())){
                          
                          String rutaImagen= "/imagenes/Dados/dado"+dados[i]+".png";
                          System.out.println(rutaImagen);
                          label.setIcon(new javax.swing.ImageIcon(getClass().getResource(rutaImagen)));
                          label.setVisible(true);
                    }
                } 
               
            }
        }

    }
    public void simularTirada(int tamAtaque, int tamDefensa){   
        int [] ataque = simularDados(tamAtaque);
        int [] defensa = simularDados(tamDefensa);
        int i = 0;
        while(i<9){
            mostrarDados(ataque,true);
            mostrarDados(defensa,false);          
            i++;
        }
        
    }
     private int[] simularDados(int cant){
        int[] dados = new int[cant];
        for(int i = 0; i< cant; i++){          
            dados[i] = (int)Math.floor(Math.random()*6+1); 
        }
        return dados;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dadoAtaque2 = new javax.swing.JLabel();
        dadoAtaque1 = new javax.swing.JLabel();
        dadoAtaque4 = new javax.swing.JLabel();
        dadoAtaque3 = new javax.swing.JLabel();
        dadoDefensa3 = new javax.swing.JLabel();
        dadoDefensa4 = new javax.swing.JLabel();
        dadoDefensa2 = new javax.swing.JLabel();
        dadoDefensa1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setIconifiable(true);
        setTitle("DADOS");

        dadoAtaque2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado2.png"))); // NOI18N
        dadoAtaque2.setName("dadoAtaque2"); // NOI18N

        dadoAtaque1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado5.png"))); // NOI18N
        dadoAtaque1.setName("dadoAtaque1"); // NOI18N

        dadoAtaque4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado3.png"))); // NOI18N
        dadoAtaque4.setName("dadoAtaque4"); // NOI18N

        dadoAtaque3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado6.png"))); // NOI18N
        dadoAtaque3.setName("dadoAtaque3"); // NOI18N

        dadoDefensa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado2.png"))); // NOI18N
        dadoDefensa3.setName("dadoDefensa3"); // NOI18N

        dadoDefensa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado4.png"))); // NOI18N
        dadoDefensa4.setName("dadoDefensa4"); // NOI18N

        dadoDefensa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado3.png"))); // NOI18N
        dadoDefensa2.setName("dadoDefensa2"); // NOI18N

        dadoDefensa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dados/dado1.png"))); // NOI18N
        dadoDefensa1.setName("dadoDefensa1"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ataque");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Defensa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dadoAtaque2)
                            .addComponent(dadoAtaque1)
                            .addComponent(dadoAtaque3)
                            .addComponent(dadoAtaque4)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dadoDefensa3)
                            .addComponent(dadoDefensa4)
                            .addComponent(dadoDefensa1)
                            .addComponent(dadoDefensa2))
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadoAtaque1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dadoDefensa1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadoDefensa2)
                    .addComponent(dadoAtaque2))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dadoDefensa3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dadoDefensa4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dadoAtaque3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dadoAtaque4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dadoAtaque1;
    private javax.swing.JLabel dadoAtaque2;
    private javax.swing.JLabel dadoAtaque3;
    private javax.swing.JLabel dadoAtaque4;
    private javax.swing.JLabel dadoDefensa1;
    private javax.swing.JLabel dadoDefensa2;
    private javax.swing.JLabel dadoDefensa3;
    private javax.swing.JLabel dadoDefensa4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
