package Interfaces;


import java.awt.Dimension;
import java.util.ArrayList;
import juego.estructura.Pais;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emanuel
 */
public class InterfaceMapa extends javax.swing.JInternalFrame {
    private InterfacePrincipal principal;
    private Mapa mapa;   
    /**
     * Creates new form GUIMapa
     */
    public InterfaceMapa(InterfacePrincipal principal) {
        initComponents();
        this.principal = principal;
        this.setSize(1018, 747);   
        this.setMaximumSize(new Dimension(1018, 747));
        
        obtenerMapa();
    }
    
    private void obtenerMapa(){
        mapa = new Mapa(principal);
        jScrollPane2.setViewportView(mapa);
        //this.setContentPane(mapa);        
        
        //panelMapa.add(mapa);
        //panelMapa.repaint();
        //
    }
    //metodoProvisorio
    public void ocultar(boolean mostrarFichas, boolean mostrarMisiles){
        mapa.mostrarFichas(mostrarFichas, mostrarMisiles);
    }
    public void actualizarFichas(ArrayList<Pais> paises, boolean mostrarFichas, boolean mostrarMisiles){
        mapa.actualizarFichas(paises,mostrarFichas, mostrarMisiles);
    }
    public void mostraMensajeGlobal(String msj){
        mapa.mostrarMensajeGloblal(msj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setIconifiable(true);
        setResizable(true);
        setTitle("MAPA");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoMapa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1066, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
