package Interfaces;


import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emanuel
 */
public class Mapa extends javax.swing.JPanel {
    private ImageIcon imagen;
    private InterfacePrincipal principal;
    /**
     * Creates new form Mapa
     */
    public Mapa(InterfacePrincipal principal) {
        initComponents();  
        panelCentroAmerica.setSize(200, 115);
        this.principal = principal;
       
      
   }



   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAmericaDelNorrte = new javax.swing.JPanel();
        lblLabrador = new javax.swing.JLabel();
        lblAlaska = new javax.swing.JLabel();
        lblTerranova = new javax.swing.JLabel();
        lblNewYork = new javax.swing.JLabel();
        lblGroenlandia = new javax.swing.JLabel();
        lblCanada = new javax.swing.JLabel();
        lblIslaVictoria = new javax.swing.JLabel();
        lblLasVegas = new javax.swing.JLabel();
        lblOregon = new javax.swing.JLabel();
        lblChicago = new javax.swing.JLabel();
        lblCalifornia = new javax.swing.JLabel();
        lblFlorida = new javax.swing.JLabel();
        lblIslandia = new javax.swing.JLabel();
        panelCentroAmerica = new javax.swing.JPanel();
        lblMexico = new javax.swing.JLabel();
        lblHonduras = new javax.swing.JLabel();
        lblElSalvador = new javax.swing.JLabel();
        lblNicaragua = new javax.swing.JLabel();
        lblCuba = new javax.swing.JLabel();
        lblJamaica = new javax.swing.JLabel();
        panelAmericaDelSur = new javax.swing.JPanel();
        lblColombia = new javax.swing.JLabel();
        lblArgentina = new javax.swing.JLabel();
        lblVenezuela = new javax.swing.JLabel();
        lblBrasil = new javax.swing.JLabel();
        lblBolivia = new javax.swing.JLabel();
        lblParaguay = new javax.swing.JLabel();
        lblChile = new javax.swing.JLabel();
        lblUruguay = new javax.swing.JLabel();
        panelAfrica = new javax.swing.JPanel();
        lblSahara = new javax.swing.JLabel();
        lblEgipto = new javax.swing.JLabel();
        lblEtiopia = new javax.swing.JLabel();
        lblNigeria = new javax.swing.JLabel();
        lblAngola = new javax.swing.JLabel();
        lblMauritania = new javax.swing.JLabel();
        lblSudafrica = new javax.swing.JLabel();
        lblMadagascar = new javax.swing.JLabel();
        panelAsia = new javax.swing.JPanel();
        lblIndia = new javax.swing.JLabel();
        lblVietnam = new javax.swing.JLabel();
        lblMalasia = new javax.swing.JLabel();
        lblCorea = new javax.swing.JLabel();
        lblJapon = new javax.swing.JLabel();
        lblKamtchatka = new javax.swing.JLabel();
        lblChukchi = new javax.swing.JLabel();
        lblChina = new javax.swing.JLabel();
        lblTurquia = new javax.swing.JLabel();
        lblArabia = new javax.swing.JLabel();
        lblIsrael = new javax.swing.JLabel();
        lblIran = new javax.swing.JLabel();
        lblRusia = new javax.swing.JLabel();
        lblChechenia = new javax.swing.JLabel();
        lblSiberia = new javax.swing.JLabel();
        panelOceania = new javax.swing.JPanel();
        lblSumatra = new javax.swing.JLabel();
        lblFilipinas = new javax.swing.JLabel();
        lblTonga = new javax.swing.JLabel();
        lblAustralia = new javax.swing.JLabel();
        lblTasmania = new javax.swing.JLabel();
        lblNuevaZelandia = new javax.swing.JLabel();
        panelAsia2 = new javax.swing.JPanel();
        lblIrak = new javax.swing.JLabel();
        lblUcrania = new javax.swing.JLabel();
        lblPolonia = new javax.swing.JLabel();
        lblSerbia = new javax.swing.JLabel();
        lblFinlandia = new javax.swing.JLabel();
        lblNoruega = new javax.swing.JLabel();
        lblGranBretaña = new javax.swing.JLabel();
        lblIrlanda = new javax.swing.JLabel();
        lblAlemania = new javax.swing.JLabel();
        lblFrancia = new javax.swing.JLabel();
        lblEspaña = new javax.swing.JLabel();
        lblPortugal = new javax.swing.JLabel();
        lblItalia = new javax.swing.JLabel();
        lblCroacia = new javax.swing.JLabel();
        lblAlbania = new javax.swing.JLabel();
        lblBielorrusia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAmericaDelNorrte.setEnabled(false);
        panelAmericaDelNorrte.setOpaque(false);
        panelAmericaDelNorrte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLabrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLabradorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLabradorMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblLabrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, 20));

        lblAlaska.setToolTipText("");
        lblAlaska.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlaskaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlaskaMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblAlaska, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lblTerranova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTerranovaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTerranovaMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblTerranova, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 83, 76));

        lblNewYork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewYorkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewYorkMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblNewYork, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 94, 60));

        lblGroenlandia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGroenlandiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGroenlandiaMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblGroenlandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 106, 50));

        lblCanada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCanadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCanadaMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblCanada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 83, 59));

        lblIslaVictoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIslaVictoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIslaVictoriaMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblIslaVictoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 83, 37));

        lblLasVegas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLasVegasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLasVegasMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblLasVegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 77, 41));

        lblOregon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOregonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOregonMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblOregon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 88, 56));

        lblChicago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChicagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblChicagoMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblChicago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 48, 34));

        lblCalifornia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCaliforniaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCaliforniaMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblCalifornia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 20));

        lblFlorida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFloridaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFloridaMouseEntered(evt);
            }
        });
        panelAmericaDelNorrte.add(lblFlorida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 61, 19));

        add(panelAmericaDelNorrte, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 21, 360, 270));

        lblIslandia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIslandiaMouseClicked(evt);
            }
        });
        add(lblIslandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 70, 64));

        panelCentroAmerica.setOpaque(false);
        panelCentroAmerica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMexicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMexicoMouseEntered(evt);
            }
        });
        panelCentroAmerica.add(lblMexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

        lblHonduras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHondurasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHondurasMouseEntered(evt);
            }
        });
        panelCentroAmerica.add(lblHonduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 30));

        lblElSalvador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblElSalvadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblElSalvadorMouseEntered(evt);
            }
        });
        panelCentroAmerica.add(lblElSalvador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 40, 30));

        lblNicaragua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNicaraguaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNicaraguaMouseEntered(evt);
            }
        });
        panelCentroAmerica.add(lblNicaragua, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 40));

        lblCuba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCubaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCubaMouseEntered(evt);
            }
        });
        panelCentroAmerica.add(lblCuba, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, 20));

        lblJamaica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJamaicaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJamaicaMouseEntered(evt);
            }
        });
        panelCentroAmerica.add(lblJamaica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 40));

        add(panelCentroAmerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 217, 140));

        panelAmericaDelSur.setOpaque(false);
        panelAmericaDelSur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblColombia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColombiaMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblColombia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 100, 50));

        lblArgentina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArgentinaMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblArgentina, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 30, 80));

        lblVenezuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVenezuelaMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblVenezuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 50));

        lblBrasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBrasilMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblBrasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 40));

        lblBolivia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBoliviaMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblBolivia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 40, 40));

        lblParaguay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblParaguayMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblParaguay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 40, 40));

        lblChile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChileMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblChile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 30, 90));

        lblUruguay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUruguayMouseClicked(evt);
            }
        });
        panelAmericaDelSur.add(lblUruguay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 50, 30));

        add(panelAmericaDelSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 430, 240, 280));

        panelAfrica.setOpaque(false);
        panelAfrica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSahara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaharaMouseClicked(evt);
            }
        });
        panelAfrica.add(lblSahara, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 70, 80));

        lblEgipto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEgiptoMouseClicked(evt);
            }
        });
        panelAfrica.add(lblEgipto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 16, 100, 40));

        lblEtiopia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEtiopiaMouseClicked(evt);
            }
        });
        panelAfrica.add(lblEtiopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 64, 100, 30));

        lblNigeria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNigeriaMouseClicked(evt);
            }
        });
        panelAfrica.add(lblNigeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, 40));

        lblAngola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAngolaMouseClicked(evt);
            }
        });
        panelAfrica.add(lblAngola, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, 30));

        lblMauritania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMauritaniaMouseClicked(evt);
            }
        });
        panelAfrica.add(lblMauritania, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 70, 30));

        lblSudafrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSudafricaMouseClicked(evt);
            }
        });
        panelAfrica.add(lblSudafrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 50, 50));

        lblMadagascar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMadagascarMouseClicked(evt);
            }
        });
        panelAfrica.add(lblMadagascar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 60, 50));

        add(panelAfrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 280, 240));

        panelAsia.setOpaque(false);
        panelAsia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIndia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIndiaMouseClicked(evt);
            }
        });
        panelAsia.add(lblIndia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 36, 58));

        lblVietnam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVietnamMouseClicked(evt);
            }
        });
        panelAsia.add(lblVietnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 70, 70));

        lblMalasia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMalasiaMouseClicked(evt);
            }
        });
        panelAsia.add(lblMalasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 264, 50, 50));

        lblCorea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCoreaMouseClicked(evt);
            }
        });
        panelAsia.add(lblCorea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 50, 80));

        lblJapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJaponMouseClicked(evt);
            }
        });
        panelAsia.add(lblJapon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 20, 90));

        lblKamtchatka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKamtchatkaMouseClicked(evt);
            }
        });
        panelAsia.add(lblKamtchatka, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 50, 100));

        lblChukchi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChukchiMouseClicked(evt);
            }
        });
        panelAsia.add(lblChukchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 60, 40));

        lblChina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChinaMouseClicked(evt);
            }
        });
        panelAsia.add(lblChina, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, 130));

        lblTurquia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTurquiaMouseClicked(evt);
            }
        });
        panelAsia.add(lblTurquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 40, 50));

        lblArabia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArabiaMouseClicked(evt);
            }
        });
        panelAsia.add(lblArabia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 50, 50));

        lblIsrael.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIsraelMouseClicked(evt);
            }
        });
        panelAsia.add(lblIsrael, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 40, 50));

        lblIran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIranMouseClicked(evt);
            }
        });
        panelAsia.add(lblIran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 30, 40));

        lblRusia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRusiaMouseClicked(evt);
            }
        });
        panelAsia.add(lblRusia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 70));

        lblChechenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChecheniaMouseClicked(evt);
            }
        });
        panelAsia.add(lblChechenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 50));

        lblSiberia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiberiaMouseClicked(evt);
            }
        });
        panelAsia.add(lblSiberia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        add(panelAsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 280, 430));

        panelOceania.setOpaque(false);
        panelOceania.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSumatra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSumatraMouseClicked(evt);
            }
        });
        panelOceania.add(lblSumatra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 49, 36));

        lblFilipinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFilipinasMouseClicked(evt);
            }
        });
        panelOceania.add(lblFilipinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 1, 50, 40));

        lblTonga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTongaMouseClicked(evt);
            }
        });
        panelOceania.add(lblTonga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, 45));

        lblAustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAustraliaMouseClicked(evt);
            }
        });
        panelOceania.add(lblAustralia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 131, 71));

        lblTasmania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTasmaniaMouseClicked(evt);
            }
        });
        panelOceania.add(lblTasmania, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 60, 23));

        lblNuevaZelandia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevaZelandiaMouseClicked(evt);
            }
        });
        panelOceania.add(lblNuevaZelandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 205, 100, 35));

        add(panelOceania, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 230, 240));

        panelAsia2.setOpaque(false);

        lblIrak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIrakMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAsia2Layout = new javax.swing.GroupLayout(panelAsia2);
        panelAsia2.setLayout(panelAsia2Layout);
        panelAsia2Layout.setHorizontalGroup(
            panelAsia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsia2Layout.createSequentialGroup()
                .addComponent(lblIrak, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        panelAsia2Layout.setVerticalGroup(
            panelAsia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsia2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIrak, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panelAsia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 40, 80));

        lblUcrania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUcraniaMouseClicked(evt);
            }
        });
        add(lblUcrania, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 40, 60));

        lblPolonia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPoloniaMouseClicked(evt);
            }
        });
        add(lblPolonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 50, 40));

        lblSerbia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSerbiaMouseClicked(evt);
            }
        });
        add(lblSerbia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 50, 30));

        lblFinlandia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFinlandiaMouseClicked(evt);
            }
        });
        add(lblFinlandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 50, 60));

        lblNoruega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoruegaMouseClicked(evt);
            }
        });
        add(lblNoruega, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 50, 80));

        lblGranBretaña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGranBretañaMouseClicked(evt);
            }
        });
        add(lblGranBretaña, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 40, 70));

        lblIrlanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIrlandaMouseClicked(evt);
            }
        });
        add(lblIrlanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 40, 40));

        lblAlemania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlemaniaMouseClicked(evt);
            }
        });
        add(lblAlemania, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 40, 70));

        lblFrancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFranciaMouseClicked(evt);
            }
        });
        add(lblFrancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 40, 60));

        lblEspaña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEspañaMouseClicked(evt);
            }
        });
        add(lblEspaña, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 60, 60));

        lblPortugal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPortugalMouseClicked(evt);
            }
        });
        add(lblPortugal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 20, 70));

        lblItalia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItaliaMouseClicked(evt);
            }
        });
        add(lblItalia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 30, 70));

        lblCroacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCroaciaMouseClicked(evt);
            }
        });
        add(lblCroacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 30, 50));

        lblAlbania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlbaniaMouseClicked(evt);
            }
        });
        add(lblAlbania, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 40, 70));

        lblBielorrusia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBielorrusiaMouseClicked(evt);
            }
        });
        add(lblBielorrusia, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 30, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teg3.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAlaskaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlaskaMouseClicked
         JOptionPane.showMessageDialog(this,"Alaska gil");
    }//GEN-LAST:event_lblAlaskaMouseClicked

    private void lblCanadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCanadaMouseClicked
        JOptionPane.showMessageDialog(this,"Canada gil");
    }//GEN-LAST:event_lblCanadaMouseClicked

    private void lblIslaVictoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIslaVictoriaMouseClicked
        JOptionPane.showMessageDialog(this,"Isla Victoria gil");
    }//GEN-LAST:event_lblIslaVictoriaMouseClicked

    private void lblGroenlandiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGroenlandiaMouseClicked
       JOptionPane.showMessageDialog(this,"Groenlandia gil");
    }//GEN-LAST:event_lblGroenlandiaMouseClicked

    private void lblIslandiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIslandiaMouseClicked
        JOptionPane.showMessageDialog(this,"Islandia gil");
    }//GEN-LAST:event_lblIslandiaMouseClicked

    private void lblLabradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLabradorMouseClicked
        JOptionPane.showMessageDialog(this,"Labrador gil");
    }//GEN-LAST:event_lblLabradorMouseClicked

    private void lblNewYorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewYorkMouseClicked
        JOptionPane.showMessageDialog(this,"New York gil");
    }//GEN-LAST:event_lblNewYorkMouseClicked

    private void lblTerranovaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTerranovaMouseClicked
        JOptionPane.showMessageDialog(this,"Terranova gil");
    }//GEN-LAST:event_lblTerranovaMouseClicked

    private void lblOregonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOregonMouseClicked
        JOptionPane.showMessageDialog(this,"Oregon gil");
    }//GEN-LAST:event_lblOregonMouseClicked

    private void lblLasVegasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLasVegasMouseClicked
        JOptionPane.showMessageDialog(this,"Las Vegas gil");
    }//GEN-LAST:event_lblLasVegasMouseClicked

    private void lblChicagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChicagoMouseClicked
        JOptionPane.showMessageDialog(this,"Chicago gil");
    }//GEN-LAST:event_lblChicagoMouseClicked

    private void lblCaliforniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaliforniaMouseClicked
        JOptionPane.showMessageDialog(this,"California gil");
    }//GEN-LAST:event_lblCaliforniaMouseClicked

    private void lblFloridaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFloridaMouseClicked
        JOptionPane.showMessageDialog(this,"Florida gil");
    }//GEN-LAST:event_lblFloridaMouseClicked

    private void lblMexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMexicoMouseClicked
        JOptionPane.showMessageDialog(this,"Mexico gil");
    }//GEN-LAST:event_lblMexicoMouseClicked

    private void lblHondurasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHondurasMouseClicked
        JOptionPane.showMessageDialog(this,"Honduras gil");
    }//GEN-LAST:event_lblHondurasMouseClicked

    private void lblElSalvadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElSalvadorMouseClicked
         JOptionPane.showMessageDialog(this,"El Salvador gil");
    }//GEN-LAST:event_lblElSalvadorMouseClicked

    private void lblNicaraguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNicaraguaMouseClicked
         JOptionPane.showMessageDialog(this,"Nicaragua gil");
    }//GEN-LAST:event_lblNicaraguaMouseClicked

    private void lblCubaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCubaMouseClicked
         JOptionPane.showMessageDialog(this,"Cuba gil");
    }//GEN-LAST:event_lblCubaMouseClicked

    private void lblJamaicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJamaicaMouseClicked
        JOptionPane.showMessageDialog(this,"Jamaica gil");
    }//GEN-LAST:event_lblJamaicaMouseClicked

    private void lblColombiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColombiaMouseClicked
        JOptionPane.showMessageDialog(this,"Colombia gil");
    }//GEN-LAST:event_lblColombiaMouseClicked

    private void lblVenezuelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVenezuelaMouseClicked
        JOptionPane.showMessageDialog(this,"Venezuela gil");
    }//GEN-LAST:event_lblVenezuelaMouseClicked

    private void lblBrasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBrasilMouseClicked
        JOptionPane.showMessageDialog(this,"Brasil gil");
    }//GEN-LAST:event_lblBrasilMouseClicked

    private void lblBoliviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBoliviaMouseClicked
       JOptionPane.showMessageDialog(this,"Bolivia gil");
    }//GEN-LAST:event_lblBoliviaMouseClicked

    private void lblParaguayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParaguayMouseClicked
        JOptionPane.showMessageDialog(this,"Paraguay gil");
    }//GEN-LAST:event_lblParaguayMouseClicked

    private void lblChileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChileMouseClicked
        JOptionPane.showMessageDialog(this,"Chile gil");
    }//GEN-LAST:event_lblChileMouseClicked

    private void lblArgentinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArgentinaMouseClicked
        JOptionPane.showMessageDialog(this,"Argentina gil");
    }//GEN-LAST:event_lblArgentinaMouseClicked

    private void lblUruguayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUruguayMouseClicked
        JOptionPane.showMessageDialog(this,"Uruguay gil");
    }//GEN-LAST:event_lblUruguayMouseClicked

    private void lblSaharaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaharaMouseClicked
        JOptionPane.showMessageDialog(this,"Sahara gil");
    }//GEN-LAST:event_lblSaharaMouseClicked

    private void lblEgiptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEgiptoMouseClicked
        JOptionPane.showMessageDialog(this,"Egipto gil");
    }//GEN-LAST:event_lblEgiptoMouseClicked

    private void lblEtiopiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEtiopiaMouseClicked
        JOptionPane.showMessageDialog(this,"Etiopia gil");
    }//GEN-LAST:event_lblEtiopiaMouseClicked

    private void lblNigeriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNigeriaMouseClicked
        JOptionPane.showMessageDialog(this,"Nigeria gil");
    }//GEN-LAST:event_lblNigeriaMouseClicked

    private void lblAngolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAngolaMouseClicked
       JOptionPane.showMessageDialog(this,"Angola gil");
    }//GEN-LAST:event_lblAngolaMouseClicked

    private void lblMauritaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMauritaniaMouseClicked
        JOptionPane.showMessageDialog(this,"Mauritania gil");
    }//GEN-LAST:event_lblMauritaniaMouseClicked

    private void lblSudafricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSudafricaMouseClicked
        JOptionPane.showMessageDialog(this,"Sudafrica gil");
    }//GEN-LAST:event_lblSudafricaMouseClicked

    private void lblMadagascarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMadagascarMouseClicked
        JOptionPane.showMessageDialog(this,"Madagascar gil");
    }//GEN-LAST:event_lblMadagascarMouseClicked

    private void lblSumatraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSumatraMouseClicked
        JOptionPane.showMessageDialog(this,"Sumatra gil");
    }//GEN-LAST:event_lblSumatraMouseClicked

    private void lblFilipinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFilipinasMouseClicked
        JOptionPane.showMessageDialog(this,"Filipinas gil"); 
    }//GEN-LAST:event_lblFilipinasMouseClicked

    private void lblTongaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTongaMouseClicked
        JOptionPane.showMessageDialog(this,"Tonga gil"); 
    }//GEN-LAST:event_lblTongaMouseClicked

    private void lblAustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAustraliaMouseClicked
         JOptionPane.showMessageDialog(this,"Australia gil"); 
    }//GEN-LAST:event_lblAustraliaMouseClicked

    private void lblTasmaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTasmaniaMouseClicked
         JOptionPane.showMessageDialog(this,"Tasmania gil"); 
    }//GEN-LAST:event_lblTasmaniaMouseClicked

    private void lblNuevaZelandiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaZelandiaMouseClicked
        JOptionPane.showMessageDialog(this,"Nueva Zelandia gil"); 
    }//GEN-LAST:event_lblNuevaZelandiaMouseClicked

    private void lblIndiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndiaMouseClicked
        JOptionPane.showMessageDialog(this,"India gil"); 
    }//GEN-LAST:event_lblIndiaMouseClicked

    private void lblVietnamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVietnamMouseClicked
        JOptionPane.showMessageDialog(this,"Vietnam gil"); 
    }//GEN-LAST:event_lblVietnamMouseClicked

    private void lblMalasiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMalasiaMouseClicked
        JOptionPane.showMessageDialog(this,"Malasia gil"); 
    }//GEN-LAST:event_lblMalasiaMouseClicked

    private void lblCoreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCoreaMouseClicked
        JOptionPane.showMessageDialog(this,"Corea gil"); 
    }//GEN-LAST:event_lblCoreaMouseClicked

    private void lblJaponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJaponMouseClicked
        JOptionPane.showMessageDialog(this,"Japon gil"); 
    }//GEN-LAST:event_lblJaponMouseClicked

    private void lblKamtchatkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKamtchatkaMouseClicked
        JOptionPane.showMessageDialog(this,"Kamtchatka gil"); 
    }//GEN-LAST:event_lblKamtchatkaMouseClicked

    private void lblChukchiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChukchiMouseClicked
        JOptionPane.showMessageDialog(this,"Chukchi gil"); 
    }//GEN-LAST:event_lblChukchiMouseClicked

    private void lblChinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChinaMouseClicked
        JOptionPane.showMessageDialog(this,"China gil"); 
    }//GEN-LAST:event_lblChinaMouseClicked

    private void lblTurquiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTurquiaMouseClicked
        JOptionPane.showMessageDialog(this,"Turquia gil");
    }//GEN-LAST:event_lblTurquiaMouseClicked

    private void lblArabiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArabiaMouseClicked
        JOptionPane.showMessageDialog(this,"Arabia gil");
    }//GEN-LAST:event_lblArabiaMouseClicked

    private void lblIsraelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIsraelMouseClicked
         JOptionPane.showMessageDialog(this,"Israel gil");
    }//GEN-LAST:event_lblIsraelMouseClicked

    private void lblIrakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIrakMouseClicked
         JOptionPane.showMessageDialog(this,"Irak gil");
    }//GEN-LAST:event_lblIrakMouseClicked

    private void lblIranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIranMouseClicked
       JOptionPane.showMessageDialog(this,"Iran gil");
    }//GEN-LAST:event_lblIranMouseClicked

    private void lblRusiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRusiaMouseClicked
        JOptionPane.showMessageDialog(this,"Rusia gil");
    }//GEN-LAST:event_lblRusiaMouseClicked

    private void lblChecheniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChecheniaMouseClicked
       JOptionPane.showMessageDialog(this,"Chechenia gil");
    }//GEN-LAST:event_lblChecheniaMouseClicked

    private void lblSiberiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiberiaMouseClicked
        JOptionPane.showMessageDialog(this,"Siberia gil");
    }//GEN-LAST:event_lblSiberiaMouseClicked

    private void lblUcraniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUcraniaMouseClicked
        JOptionPane.showMessageDialog(this,"Ucrania gil");
    }//GEN-LAST:event_lblUcraniaMouseClicked

    private void lblPoloniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPoloniaMouseClicked
        JOptionPane.showMessageDialog(this,"Polonia gil");
    }//GEN-LAST:event_lblPoloniaMouseClicked

    private void lblSerbiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSerbiaMouseClicked
        JOptionPane.showMessageDialog(this,"Serbia gil");
    }//GEN-LAST:event_lblSerbiaMouseClicked

    private void lblFinlandiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinlandiaMouseClicked
        JOptionPane.showMessageDialog(this,"Finlandia gil");
    }//GEN-LAST:event_lblFinlandiaMouseClicked

    private void lblNoruegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoruegaMouseClicked
        JOptionPane.showMessageDialog(this,"Noruega gil");
    }//GEN-LAST:event_lblNoruegaMouseClicked

    private void lblGranBretañaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGranBretañaMouseClicked
        JOptionPane.showMessageDialog(this,"Gran Bretaña gil");
    }//GEN-LAST:event_lblGranBretañaMouseClicked

    private void lblIrlandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIrlandaMouseClicked
        JOptionPane.showMessageDialog(this,"Irlanda gil");
    }//GEN-LAST:event_lblIrlandaMouseClicked

    private void lblAlemaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlemaniaMouseClicked
        JOptionPane.showMessageDialog(this,"Alemania gil");
    }//GEN-LAST:event_lblAlemaniaMouseClicked

    private void lblFranciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFranciaMouseClicked
        JOptionPane.showMessageDialog(this,"Francia gil");
    }//GEN-LAST:event_lblFranciaMouseClicked

    private void lblEspañaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspañaMouseClicked
        JOptionPane.showMessageDialog(this,"España gil");
    }//GEN-LAST:event_lblEspañaMouseClicked

    private void lblPortugalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPortugalMouseClicked
        JOptionPane.showMessageDialog(this,"Portugal gil");
    }//GEN-LAST:event_lblPortugalMouseClicked

    private void lblItaliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItaliaMouseClicked
        JOptionPane.showMessageDialog(this,"Italia gil");
    }//GEN-LAST:event_lblItaliaMouseClicked

    private void lblCroaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCroaciaMouseClicked
        JOptionPane.showMessageDialog(this,"Croacia gil");
    }//GEN-LAST:event_lblCroaciaMouseClicked

    private void lblAlbaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlbaniaMouseClicked
        JOptionPane.showMessageDialog(this,"Albania gil");
    }//GEN-LAST:event_lblAlbaniaMouseClicked

    private void lblBielorrusiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBielorrusiaMouseClicked
        JOptionPane.showMessageDialog(this,"BieloRrusia gil");
    }//GEN-LAST:event_lblBielorrusiaMouseClicked

    private void lblAlaskaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlaskaMouseEntered
        principal.cargarInformacionPais("ALASKA");
    }//GEN-LAST:event_lblAlaskaMouseEntered

    private void lblCanadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCanadaMouseEntered
        principal.cargarInformacionPais("CANADA");
    }//GEN-LAST:event_lblCanadaMouseEntered

    private void lblTerranovaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTerranovaMouseEntered
        principal.cargarInformacionPais("TERRANOVA");
    }//GEN-LAST:event_lblTerranovaMouseEntered

    private void lblOregonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOregonMouseEntered
        principal.cargarInformacionPais("OREGON");
    }//GEN-LAST:event_lblOregonMouseEntered

    private void lblFloridaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFloridaMouseEntered
        principal.cargarInformacionPais("FLORIDA");
    }//GEN-LAST:event_lblFloridaMouseEntered

    private void lblGroenlandiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGroenlandiaMouseEntered
        principal.cargarInformacionPais("GROENLANDIA");
    }//GEN-LAST:event_lblGroenlandiaMouseEntered

    private void lblNewYorkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewYorkMouseEntered
        principal.cargarInformacionPais("NEW YORK");
    }//GEN-LAST:event_lblNewYorkMouseEntered

    private void lblLasVegasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLasVegasMouseEntered
       principal.cargarInformacionPais("LAS VEGAS");
    }//GEN-LAST:event_lblLasVegasMouseEntered

    private void lblIslaVictoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIslaVictoriaMouseEntered
        principal.cargarInformacionPais("ISLA VICTORIA");
    }//GEN-LAST:event_lblIslaVictoriaMouseEntered

    private void lblChicagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChicagoMouseEntered
        principal.cargarInformacionPais("CHICAGO");
    }//GEN-LAST:event_lblChicagoMouseEntered

    private void lblCaliforniaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaliforniaMouseEntered
       principal.cargarInformacionPais("CALIFORNIA");
    }//GEN-LAST:event_lblCaliforniaMouseEntered

    private void lblLabradorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLabradorMouseEntered
        principal.cargarInformacionPais("LABRADOR");
    }//GEN-LAST:event_lblLabradorMouseEntered

    private void lblMexicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMexicoMouseEntered
        principal.cargarInformacionPais("MEXICO");
    }//GEN-LAST:event_lblMexicoMouseEntered

    private void lblHondurasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHondurasMouseEntered
        principal.cargarInformacionPais("HONDURAS");
    }//GEN-LAST:event_lblHondurasMouseEntered

    private void lblElSalvadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElSalvadorMouseEntered
        principal.cargarInformacionPais("EL SALVADOR");
    }//GEN-LAST:event_lblElSalvadorMouseEntered

    private void lblNicaraguaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNicaraguaMouseEntered
        principal.cargarInformacionPais("NICARAGUA");
    }//GEN-LAST:event_lblNicaraguaMouseEntered

    private void lblCubaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCubaMouseEntered
       principal.cargarInformacionPais("CUBA");
    }//GEN-LAST:event_lblCubaMouseEntered

    private void lblJamaicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJamaicaMouseEntered
        principal.cargarInformacionPais("JAMAICA");
    }//GEN-LAST:event_lblJamaicaMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlaska;
    private javax.swing.JLabel lblAlbania;
    private javax.swing.JLabel lblAlemania;
    private javax.swing.JLabel lblAngola;
    private javax.swing.JLabel lblArabia;
    private javax.swing.JLabel lblArgentina;
    private javax.swing.JLabel lblAustralia;
    private javax.swing.JLabel lblBielorrusia;
    private javax.swing.JLabel lblBolivia;
    private javax.swing.JLabel lblBrasil;
    private javax.swing.JLabel lblCalifornia;
    private javax.swing.JLabel lblCanada;
    private javax.swing.JLabel lblChechenia;
    private javax.swing.JLabel lblChicago;
    private javax.swing.JLabel lblChile;
    private javax.swing.JLabel lblChina;
    private javax.swing.JLabel lblChukchi;
    private javax.swing.JLabel lblColombia;
    private javax.swing.JLabel lblCorea;
    private javax.swing.JLabel lblCroacia;
    private javax.swing.JLabel lblCuba;
    private javax.swing.JLabel lblEgipto;
    private javax.swing.JLabel lblElSalvador;
    private javax.swing.JLabel lblEspaña;
    private javax.swing.JLabel lblEtiopia;
    private javax.swing.JLabel lblFilipinas;
    private javax.swing.JLabel lblFinlandia;
    private javax.swing.JLabel lblFlorida;
    private javax.swing.JLabel lblFrancia;
    private javax.swing.JLabel lblGranBretaña;
    private javax.swing.JLabel lblGroenlandia;
    private javax.swing.JLabel lblHonduras;
    private javax.swing.JLabel lblIndia;
    private javax.swing.JLabel lblIrak;
    private javax.swing.JLabel lblIran;
    private javax.swing.JLabel lblIrlanda;
    private javax.swing.JLabel lblIslaVictoria;
    private javax.swing.JLabel lblIslandia;
    private javax.swing.JLabel lblIsrael;
    private javax.swing.JLabel lblItalia;
    private javax.swing.JLabel lblJamaica;
    private javax.swing.JLabel lblJapon;
    private javax.swing.JLabel lblKamtchatka;
    private javax.swing.JLabel lblLabrador;
    private javax.swing.JLabel lblLasVegas;
    private javax.swing.JLabel lblMadagascar;
    private javax.swing.JLabel lblMalasia;
    private javax.swing.JLabel lblMauritania;
    private javax.swing.JLabel lblMexico;
    private javax.swing.JLabel lblNewYork;
    private javax.swing.JLabel lblNicaragua;
    private javax.swing.JLabel lblNigeria;
    private javax.swing.JLabel lblNoruega;
    private javax.swing.JLabel lblNuevaZelandia;
    private javax.swing.JLabel lblOregon;
    private javax.swing.JLabel lblParaguay;
    private javax.swing.JLabel lblPolonia;
    private javax.swing.JLabel lblPortugal;
    private javax.swing.JLabel lblRusia;
    private javax.swing.JLabel lblSahara;
    private javax.swing.JLabel lblSerbia;
    private javax.swing.JLabel lblSiberia;
    private javax.swing.JLabel lblSudafrica;
    private javax.swing.JLabel lblSumatra;
    private javax.swing.JLabel lblTasmania;
    private javax.swing.JLabel lblTerranova;
    private javax.swing.JLabel lblTonga;
    private javax.swing.JLabel lblTurquia;
    private javax.swing.JLabel lblUcrania;
    private javax.swing.JLabel lblUruguay;
    private javax.swing.JLabel lblVenezuela;
    private javax.swing.JLabel lblVietnam;
    private javax.swing.JPanel panelAfrica;
    private javax.swing.JPanel panelAmericaDelNorrte;
    private javax.swing.JPanel panelAmericaDelSur;
    private javax.swing.JPanel panelAsia;
    private javax.swing.JPanel panelAsia2;
    private javax.swing.JPanel panelCentroAmerica;
    private javax.swing.JPanel panelOceania;
    // End of variables declaration//GEN-END:variables
}
