/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import juego.estructura.TarjetaPais;


/**
 *
 * @author Emanuel
 */
public class Tarjetas extends javax.swing.JInternalFrame {
    ArrayList<TarjetaPais> tarjetas;  
    private JMenuItem menu;
    private JButton boton;
    /**
     * Creates new form Tarjetas
     */
    public Tarjetas(ArrayList<TarjetaPais> tarjetas, JMenuItem menu, JButton boton) {
        initComponents();
        this.tarjetas = tarjetas;
        limpiarLabels();
        this.boton = boton;
        this.menu = menu;
        cargarTarjetas();
    }
    private void cargarTarjetas(){
        if(tarjetas == null) return;
        for(int i = 0; i<tarjetas.size()-1; i++){
            switch(i){
                case(0): cargarTarjeta(lblTarjeta1,tarjetas.get(0).getPais().getNombre());
                case(1): cargarTarjeta(lblTarjeta2,tarjetas.get(1).getPais().getNombre());
                case(2): cargarTarjeta(lblTarjeta3,tarjetas.get(2).getPais().getNombre());
                case(3): cargarTarjeta(lblTarjeta4,tarjetas.get(3).getPais().getNombre());
                case(4): cargarTarjeta(lblTarjeta5,tarjetas.get(4).getPais().getNombre());    
            }
        }
    }
    private void cargarTarjeta(JLabel label, String pais){
        try{
            label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/"+pais.replaceAll(" ", "")+".png")));
        }
        catch(Exception e){
            
        }
    }
    private void limpiarLabels(){      
        lblTarjeta1.setIcon(null);
        lblTarjeta2.setIcon(null);
        lblTarjeta3.setIcon(null);
        lblTarjeta4.setIcon(null);
        lblTarjeta5.setIcon(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTarjeta1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTarjeta2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTarjeta3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblTarjeta4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblTarjeta5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Canje De Tarjetas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canje.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TARJETAS DISPONIBLES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 590, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canje.png"))); // NOI18N
        jButton1.setText("Canjear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel2.add(lblTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 147));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel4.add(lblTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, 147));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel5.add(lblTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 100, 147));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel6.add(lblTarjeta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 147));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel7.add(lblTarjeta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 147));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
       menu.setEnabled(true);
       boton.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblTarjeta1;
    private javax.swing.JLabel lblTarjeta2;
    private javax.swing.JLabel lblTarjeta3;
    private javax.swing.JLabel lblTarjeta4;
    private javax.swing.JLabel lblTarjeta5;
    // End of variables declaration//GEN-END:variables
}
