/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import juego.estructura.Canjeable;
import juego.estructura.TarjetaPais;


/**
 *
 * @author Emanuel
 */
public class Tarjetas extends javax.swing.JInternalFrame {
    private List<Canjeable> tarjetas;  
    private JMenuItem menu;
    private JButton boton;
    private List<Canjeable> tarjetasSeleccionadas = new ArrayList<Canjeable>();    
    /**
     * Creates new form Tarjetas
     */
    public Tarjetas(List<Canjeable> tarjetas, JMenuItem menu, JButton boton) {
        initComponents();
        this.tarjetas = (ArrayList)tarjetas;
        limpiarLabels();
        this.boton = boton;
        this.menu = menu;
        deshabilitarChecks();
        btnCanjear.setEnabled(false);
        if(FachadaInterface.esMiTurno(FachadaInterface.getJugadorLocal())){
             cargarTarjetas();   
        }    
    }
    private void cargarTarjetas(){
        if(tarjetas == null) return;
        for(int i = 0; i<tarjetas.size()-1; i++){
            switch(i){
                case(0): cargarTarjeta(lblTarjeta1,tarjetas.get(0).getNombrePais());
                         chkTarjeta1.setEnabled(true);
                         break;
                case(1): cargarTarjeta(lblTarjeta2,tarjetas.get(1).getNombrePais());
                         chkTarjeta2.setEnabled(true);
                         break;
                case(2): cargarTarjeta(lblTarjeta3,tarjetas.get(2).getNombrePais());
                         chkTarjeta3.setEnabled(true);
                         break;
                case(3): cargarTarjeta(lblTarjeta4,tarjetas.get(3).getNombrePais());
                         chkTarjeta4.setEnabled(true);
                         break;
                case(4): cargarTarjeta(lblTarjeta5,tarjetas.get(4).getNombrePais());    
                         chkTarjeta5.setEnabled(true);
                         break;
            }
        }
    }
    private void deshabilitarChecks(){
        chkTarjeta1.setEnabled(false);
        chkTarjeta2.setEnabled(false);
        chkTarjeta3.setEnabled(false);
        chkTarjeta4.setEnabled(false);
        chkTarjeta5.setEnabled(false);
    }
    private void cargarTarjeta(JLabel label, String pais){
        try{
            label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/"+pais.replaceAll(" ", "")+".png")));
        }
        catch(Exception e){
            
        }
    }
    private void limpiarLabels(){      
        lblTarjeta1.setIcon(null);
        lblTarjeta2.setIcon(null);
        lblTarjeta3.setIcon(null);
        lblTarjeta4.setIcon(null);
        lblTarjeta5.setIcon(null);
    }
    private boolean puedoCanjear(){
        return FachadaInterface.canjeValido(FachadaInterface.getJugadorLocal(),tarjetasSeleccionadas);
    }
    private boolean cargarTarjetaSeleccionada(Canjeable tarjeta){
        if(tarjetasSeleccionadas.size() <3){           
            if(puedoCanjear()){
                JOptionPane.showMessageDialog(this,"Ya Posee las tarjetas suficientes para realizar un canje", "Canje", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            tarjetasSeleccionadas.add(tarjeta);
            if(puedoCanjear()) btnCanjear.setEnabled(true);
            else btnCanjear.setEnabled(false);
            return true;
        }
        else{
            JOptionPane.showMessageDialog(this, "A llegado al maximo de tarjetas para canjear", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
     private void quitarTarjetasSelccionada(Canjeable tarjeta){
        tarjetasSeleccionadas.remove(tarjeta);  
        if(puedoCanjear()){
            btnCanjear.setEnabled(true);
        }
        else{
            btnCanjear.setEnabled(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCanjear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTarjeta1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTarjeta2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTarjeta3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblTarjeta4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblTarjeta5 = new javax.swing.JLabel();
        chkTarjeta5 = new javax.swing.JCheckBox();
        chkTarjeta1 = new javax.swing.JCheckBox();
        chkTarjeta2 = new javax.swing.JCheckBox();
        chkTarjeta3 = new javax.swing.JCheckBox();
        chkTarjeta4 = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Canje De Tarjetas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canje.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TARJETAS DISPONIBLES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 590, -1));

        btnCanjear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canje.png"))); // NOI18N
        btnCanjear.setText("Canjear");
        btnCanjear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanjearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanjear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel2.add(lblTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 147));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel4.add(lblTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, 147));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel5.add(lblTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 100, 147));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel6.add(lblTarjeta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 147));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarjeta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjetas/alaska.png"))); // NOI18N
        jPanel7.add(lblTarjeta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 98, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 147));

        chkTarjeta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTarjeta5ActionPerformed(evt);
            }
        });
        jPanel1.add(chkTarjeta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        chkTarjeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTarjeta1ActionPerformed(evt);
            }
        });
        jPanel1.add(chkTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        chkTarjeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTarjeta2ActionPerformed(evt);
            }
        });
        jPanel1.add(chkTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        chkTarjeta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTarjeta3ActionPerformed(evt);
            }
        });
        jPanel1.add(chkTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        chkTarjeta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTarjeta4ActionPerformed(evt);
            }
        });
        jPanel1.add(chkTarjeta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanjearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanjearActionPerformed
        FachadaInterface.canjearTarjeta(FachadaInterface.getJugadorLocal(), tarjetasSeleccionadas);
        this.dispose();
    }//GEN-LAST:event_btnCanjearActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
       menu.setEnabled(true);
       boton.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosing

    private void chkTarjeta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTarjeta5ActionPerformed
        if(chkTarjeta5.isSelected()){
             if(!cargarTarjetaSeleccionada(tarjetas.get(4))){
                chkTarjeta5.setSelected(false);                
            }
        }
        else{
            quitarTarjetasSelccionada(tarjetas.get(4));
        }
    }//GEN-LAST:event_chkTarjeta5ActionPerformed

    private void chkTarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTarjeta1ActionPerformed
        if(chkTarjeta1.isSelected()){
             if(!cargarTarjetaSeleccionada(tarjetas.get(0))){
                chkTarjeta1.setSelected(false);                
            }
        }
        else{
            quitarTarjetasSelccionada(tarjetas.get(0));
        }
    }//GEN-LAST:event_chkTarjeta1ActionPerformed

    private void chkTarjeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTarjeta2ActionPerformed
        if(chkTarjeta2.isSelected()){
            if(!cargarTarjetaSeleccionada(tarjetas.get(1))){
                chkTarjeta2.setSelected(false);                
            }
        }
        else{
            quitarTarjetasSelccionada(tarjetas.get(1));
        }
    }//GEN-LAST:event_chkTarjeta2ActionPerformed

    private void chkTarjeta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTarjeta3ActionPerformed
        if(chkTarjeta3.isSelected()){
            if(!cargarTarjetaSeleccionada(tarjetas.get(2))){
                chkTarjeta3.setSelected(false);                
            }
        }
        else{
            quitarTarjetasSelccionada(tarjetas.get(2));
        }
    }//GEN-LAST:event_chkTarjeta3ActionPerformed

    private void chkTarjeta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTarjeta4ActionPerformed
        if(chkTarjeta4.isSelected()){
            if(!cargarTarjetaSeleccionada(tarjetas.get(3))){
                chkTarjeta4.setSelected(false);                
            }
        }
        else{
            quitarTarjetasSelccionada(tarjetas.get(3));
        }
    }//GEN-LAST:event_chkTarjeta4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanjear;
    private javax.swing.JCheckBox chkTarjeta1;
    private javax.swing.JCheckBox chkTarjeta2;
    private javax.swing.JCheckBox chkTarjeta3;
    private javax.swing.JCheckBox chkTarjeta4;
    private javax.swing.JCheckBox chkTarjeta5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblTarjeta1;
    private javax.swing.JLabel lblTarjeta2;
    private javax.swing.JLabel lblTarjeta3;
    private javax.swing.JLabel lblTarjeta4;
    private javax.swing.JLabel lblTarjeta5;
    // End of variables declaration//GEN-END:variables
}
