/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.servidor;

import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.text.DefaultCaret;
import modelo.logger.LogItem;
import modelo.logger.Logger;

/**
 *
 * @author heril
 */
public class AdministracionPartida extends javax.swing.JFrame {

    private static AdministracionPartida instance = null;
    
    /**
     * Creates new form SalaEspera
     */
    private AdministracionPartida() {
        initComponents();
        inicio();
    }
    
    public static AdministracionPartida getInstance() {
        if (instance == null) {
            instance = new AdministracionPartida();
        }
        return instance;
    }
    
    /**
     * Personal method for initializing the form.
     * Called from the constructor after initComponents()
     */
    private void inicio() {
        addKeyListenerToChatField();
        addCloseListenerToFrame();
    }
    
    private void addCloseListenerToFrame() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                e.getWindow().setVisible(false);
                Logger.getInstance().addLogItem(new LogItem("Ventana servidor ha sido oculta."));
            }

            @Override
            public void windowOpened(WindowEvent e) {
                Logger.getInstance().addLogItem(new LogItem("Ventana servidor ha sido abierta."));
            }
        });
    }
    
    /**
     *KeyListener add to txtChatPersonal, called when <ENTER> is pressed.
     */
    private void addKeyListenerToChatField() {
        txtChatPersonal.addKeyListener(new java.awt.event.KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnEnviarChatActionPerformed(null);
                }
            }
            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroJuego = new javax.swing.JLabel();
        sPanelJugadores = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();
        txtChatPersonal = new javax.swing.JTextField();
        btnEnviarChat = new javax.swing.JButton();
        sPanelChat = new javax.swing.JScrollPane();
        txtChatArea = new javax.swing.JTextArea();
        menuPrincipal = new javax.swing.JMenuBar();
        menuItemSala = new javax.swing.JMenu();
        menuItemEstablecerContraseña = new javax.swing.JMenuItem();
        menuItemCargarPartida = new javax.swing.JMenuItem();
        menuItemGuardarPartida = new javax.swing.JMenuItem();
        menuItemCerrarSala = new javax.swing.JMenuItem();
        menuItemJugadores = new javax.swing.JMenu();
        menuItemAgregarJugadorIA = new javax.swing.JMenuItem();
        menuItemPartida = new javax.swing.JMenu();
        menuItemComenzarPartida = new javax.swing.JMenuItem();
        menuItemPausarPartida = new javax.swing.JMenuItem();

        setTitle("TEG - Administracion de partida");
        setResizable(false);

        lblNumeroJuego.setText("Numero de juego: <VALOR_ALEATORIO>");

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Alias", "Tipo", "Color", "Listo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sPanelJugadores.setViewportView(tblJugadores);

        btnEnviarChat.setText("Enviar");
        btnEnviarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarChatActionPerformed(evt);
            }
        });

        txtChatArea.setEditable(false);
        txtChatArea.setColumns(20);
        txtChatArea.setLineWrap(true);
        txtChatArea.setRows(1);
        sPanelChat.setViewportView(txtChatArea);

        menuItemSala.setText("Sala");

        menuItemEstablecerContraseña.setText("Establecer contraseña");
        menuItemSala.add(menuItemEstablecerContraseña);

        menuItemCargarPartida.setText("Cargar partida");
        menuItemSala.add(menuItemCargarPartida);

        menuItemGuardarPartida.setText("Guardar partida");
        menuItemSala.add(menuItemGuardarPartida);

        menuItemCerrarSala.setText("Cerrar sala");
        menuItemSala.add(menuItemCerrarSala);

        menuPrincipal.add(menuItemSala);

        menuItemJugadores.setText("Jugadores");

        menuItemAgregarJugadorIA.setText("Agregar jugador IA");
        menuItemJugadores.add(menuItemAgregarJugadorIA);

        menuPrincipal.add(menuItemJugadores);

        menuItemPartida.setText("Partida");

        menuItemComenzarPartida.setText("Comenzar partida");
        menuItemPartida.add(menuItemComenzarPartida);

        menuItemPausarPartida.setText("Pausar partida");
        menuItemPartida.add(menuItemPausarPartida);

        menuPrincipal.add(menuItemPartida);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sPanelChat)
                    .addComponent(sPanelJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(lblNumeroJuego, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtChatPersonal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarChat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumeroJuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sPanelJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sPanelChat, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChatPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarChat))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarChatActionPerformed
        String chat = txtChatPersonal.getText();
        if (chat != null && chat.isEmpty()) {
            return;
        }
        txtChatArea.append(txtChatPersonal.getText() + "\n");
        DefaultCaret caret = (DefaultCaret)txtChatPersonal.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        txtChatPersonal.setText("");
    }//GEN-LAST:event_btnEnviarChatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarChat;
    private javax.swing.JLabel lblNumeroJuego;
    private javax.swing.JMenuItem menuItemAgregarJugadorIA;
    private javax.swing.JMenuItem menuItemCargarPartida;
    private javax.swing.JMenuItem menuItemCerrarSala;
    private javax.swing.JMenuItem menuItemComenzarPartida;
    private javax.swing.JMenuItem menuItemEstablecerContraseña;
    private javax.swing.JMenuItem menuItemGuardarPartida;
    private javax.swing.JMenu menuItemJugadores;
    private javax.swing.JMenu menuItemPartida;
    private javax.swing.JMenuItem menuItemPausarPartida;
    private javax.swing.JMenu menuItemSala;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JScrollPane sPanelChat;
    private javax.swing.JScrollPane sPanelJugadores;
    private javax.swing.JTable tblJugadores;
    private javax.swing.JTextArea txtChatArea;
    private javax.swing.JTextField txtChatPersonal;
    // End of variables declaration//GEN-END:variables
}
